//! Provider-agnostic post-stream pipeline (Sprint v6 Phase 6).
//!
//! Centralises the deterministic per-turn analysis that runs AFTER the
//! streaming loop finishes:
//!
//! 1. Count fetch tool calls (used by the verifier's `should_verify_with_context`
//!    gate to spot unsourced numeric claims).
//! 2. Run the live response-lint over a partial `PersistedRun` built from the
//!    turn's message transcript. Emits [`LlmDelta::LintFindings`] when at
//!    least one rule fires.
//! 3. Parse the tool transcript so the CoVe verifier (run by the caller) can
//!    ground build-specific claims against `get_active_build` + `pob_calc`
//!    payloads.
//!
//! The CoVe verifier itself stays in the provider's `run` method because
//! its sub-calls (extract / judge / revise) require Anthropic-shaped HTTP
//! credentials. Ollama opt-in via secondary `AnthropicClient::from_env`.
//!
//! ## Wire-format normalisation
//!
//! All helpers below expect `messages` to be in Anthropic-native shape:
//! `{role, content: [{type, ...blocks}]}`. Ollama uses OpenAI-native
//! shape (`{role, content: "string", tool_calls: [...]}`); callers on
//! that provider MUST convert first via [`messages_openai_to_anthropic`].
//! The converter is lossy by design — only the fields the post-stream
//! pipeline reads survive.

use serde_json::{json, Value};
use tokio::sync::mpsc;

use crate::llm::recorder::{ChatStats, PersistedRun, PersistedSegment};
use crate::llm::verifier::ToolTranscript;
use crate::llm::LlmDelta;
use crate::test_runner::response_lint::lint_run;

/// Tools whose `tool_use` blocks count as a "fetch" — i.e. a same-turn
/// authoritative source for numeric claims. Mirror of the constant the
/// verifier uses to gate `should_verify_with_context`. Kept inline (not
/// re-exported from verifier.rs) so this module stays self-contained.
const FETCH_TOOLS: &[&str] = &[
    "wiki_parse",
    "wiki_cargo",
    "wiki_search",
    "wiki_synergies",
    "repoe_lookup",
    "pob_calc",
    "web_fetch",
];

/// Return type of [`run_shared_post_stream`]. Carries the two values the
/// caller still needs to invoke the provider-specific verifier; lint
/// findings have already been emitted via the deltas channel by the time
/// this struct is returned.
pub struct SharedPostStreamOutcome {
    pub fetch_tool_calls: usize,
    pub transcript: ToolTranscript,
}

/// Run the deterministic part of the post-stream pipeline. Emits
/// `LlmDelta::LintFindings` when lint produces findings. Returns the
/// fetch count and parsed tool transcript so the caller can wire them
/// into a provider-specific verifier call.
///
/// `messages` MUST be in Anthropic-native format. Callers running on
/// providers that use a different wire format (OpenAI-style Ollama)
/// must convert first via [`messages_openai_to_anthropic`].
pub fn run_shared_post_stream(
    messages: &[Value],
    full_assistant: &str,
    deltas: &mpsc::UnboundedSender<LlmDelta>,
    provider_label: &str,
) -> SharedPostStreamOutcome {
    let fetch_tool_calls = count_fetch_tool_calls(messages);
    let lint_input = build_partial_lint_run(messages, full_assistant, provider_label);
    let lint_report = lint_run(&lint_input);
    if !lint_report.findings.is_empty() {
        let _ = deltas.send(LlmDelta::LintFindings {
            findings: lint_report.findings,
        });
    }
    let transcript = ToolTranscript::from_messages(messages);
    SharedPostStreamOutcome {
        fetch_tool_calls,
        transcript,
    }
}

/// Convert OpenAI-native messages (as Ollama produces) into Anthropic-native
/// shape so the shared helpers above (which expect content arrays and typed
/// blocks) work unchanged.
///
/// The conversion is intentionally lossy — only the fields read by
/// `count_fetch_tool_calls`, `segments_from_messages`, and
/// `ToolTranscript::from_messages` are preserved:
///
/// * `{role: "user"|"assistant", content: "..."}` →
///   `{role, content: [{type: "text", text: "..."}]}` (empty text skipped).
/// * `{role: "assistant", content, tool_calls: [{function: {name, arguments}, id?}]}` →
///   `{role: "assistant", content: [text? + tool_use(s)...]}` with each
///   tool call becoming `{type: "tool_use", id, name, input}`. Missing
///   tool ids are autogenerated as `"ollama-{name}-{idx}"`; string
///   arguments are parsed as JSON (`{}` on parse failure) so the
///   downstream `input` is always an object.
/// * `{role: "tool", name, content}` → `{role: "user", content: [{type:
///   "tool_result", tool_use_id, content}]}`. The `tool_use_id` is
///   matched to the most-recent unmatched assistant tool_use with the
///   same `name`; orphaned tool results (no preceding match) are
///   skipped silently.
/// * `{role: "system", content: "..."}` is dropped (Anthropic carries
///   system content in a separate top-level field, not in `messages`).
pub fn messages_openai_to_anthropic(messages: &[Value]) -> Vec<Value> {
    let mut out: Vec<Value> = Vec::with_capacity(messages.len());
    // Track the assistant's tool_use blocks by name in insertion order so a
    // following `{role: "tool", name, ...}` can grab the next unmatched id.
    // Each entry is `(name, id, consumed)`. We avoid HashMap here because a
    // single turn can dispatch the same tool multiple times.
    let mut pending: Vec<(String, String, bool)> = Vec::new();
    let mut tool_call_idx: usize = 0;

    for m in messages {
        let role = m.get("role").and_then(|v| v.as_str()).unwrap_or("");
        match role {
            "system" => {
                // Anthropic carries system content separately; drop here.
                continue;
            }
            "user" => {
                let Some(text) = m.get("content").and_then(|v| v.as_str()) else {
                    // Unexpected shape — pass through verbatim so the
                    // downstream helpers can ignore it without panicking.
                    out.push(m.clone());
                    continue;
                };
                if text.is_empty() {
                    continue;
                }
                out.push(json!({
                    "role": "user",
                    "content": [{"type": "text", "text": text}],
                }));
            }
            "assistant" => {
                let text = m
                    .get("content")
                    .and_then(|v| v.as_str())
                    .unwrap_or("")
                    .to_string();
                let tool_calls = m
                    .get("tool_calls")
                    .and_then(|v| v.as_array())
                    .cloned()
                    .unwrap_or_default();

                let mut blocks: Vec<Value> = Vec::new();
                if !text.is_empty() {
                    blocks.push(json!({"type": "text", "text": text}));
                }
                for call in &tool_calls {
                    let function = call.get("function").cloned().unwrap_or(Value::Null);
                    let name = function
                        .get("name")
                        .and_then(|s| s.as_str())
                        .unwrap_or("")
                        .to_string();
                    if name.is_empty() {
                        continue;
                    }
                    // Arguments may be either an Object or a JSON-encoded
                    // String depending on the Ollama model. Normalise to
                    // a parsed Value so the downstream `input` field is
                    // always an object.
                    let input = match function.get("arguments") {
                        Some(Value::Object(_)) => {
                            function.get("arguments").cloned().unwrap_or(json!({}))
                        }
                        Some(Value::String(s)) => serde_json::from_str(s).unwrap_or(json!({})),
                        Some(other) => other.clone(),
                        None => json!({}),
                    };
                    let id = call
                        .get("id")
                        .and_then(|v| v.as_str())
                        .map(|s| s.to_string())
                        .filter(|s| !s.is_empty())
                        .unwrap_or_else(|| {
                            tool_call_idx += 1;
                            format!("ollama-{name}-{tool_call_idx}")
                        });
                    pending.push((name.clone(), id.clone(), false));
                    blocks.push(json!({
                        "type": "tool_use",
                        "id": id,
                        "name": name,
                        "input": input,
                    }));
                }
                if blocks.is_empty() {
                    continue;
                }
                out.push(json!({
                    "role": "assistant",
                    "content": blocks,
                }));
            }
            "tool" => {
                let name = m
                    .get("name")
                    .and_then(|v| v.as_str())
                    .unwrap_or("")
                    .to_string();
                let content = m
                    .get("content")
                    .map(|v| {
                        v.as_str()
                            .map(|s| s.to_string())
                            .unwrap_or_else(|| v.to_string())
                    })
                    .unwrap_or_default();
                if name.is_empty() {
                    continue;
                }
                // Find the next unmatched pending tool_use with the same name.
                let matched_id = pending
                    .iter_mut()
                    .find(|(n, _, consumed)| !*consumed && n == &name)
                    .map(|entry| {
                        entry.2 = true;
                        entry.1.clone()
                    });
                let Some(tool_use_id) = matched_id else {
                    tracing::debug!(
                        target: "bestel.post_stream",
                        tool = %name,
                        "orphan tool result: no matching preceding tool_use",
                    );
                    continue;
                };
                out.push(json!({
                    "role": "user",
                    "content": [{
                        "type": "tool_result",
                        "tool_use_id": tool_use_id,
                        "content": content,
                    }],
                }));
            }
            _ => {
                // Unknown role — pass through so we don't lose information.
                out.push(m.clone());
            }
        }
    }
    out
}

/// Count the assistant `tool_use` blocks whose tool name is one of the
/// authoritative-source tools. Mirror of the helper that used to live in
/// `anthropic.rs::count_fetch_tool_calls`. Used by the verifier gate to
/// decide whether numeric claims in the draft are sourced (≥1 fetch this
/// turn) or recalled from training data (0 fetches).
fn count_fetch_tool_calls(messages: &[Value]) -> usize {
    let mut count = 0usize;
    for m in messages {
        if m.get("role").and_then(|v| v.as_str()) != Some("assistant") {
            continue;
        }
        let Some(content) = m.get("content").and_then(|c| c.as_array()) else {
            continue;
        };
        for block in content {
            if block.get("type").and_then(|t| t.as_str()) != Some("tool_use") {
                continue;
            }
            let Some(name) = block.get("name").and_then(|n| n.as_str()) else {
                continue;
            };
            if FETCH_TOOLS.contains(&name) {
                count += 1;
            }
        }
    }
    count
}

/// Sprint v6 Phase 2 helper — convert Anthropic-format tool_use/tool_result
/// blocks from `messages` into [`PersistedSegment::Tool`] entries the
/// response-lint rules can reason about. Status mapping: `is_error: true`
/// on the matching `tool_result` → `failed`; otherwise → `done`. A
/// `tool_use` without a matching `tool_result` stays `running` so
/// `tool_succeeded` returns false and lint rules behave conservatively.
fn segments_from_messages(messages: &[Value]) -> Vec<PersistedSegment> {
    let mut segments: Vec<PersistedSegment> = Vec::new();
    let mut tool_idx: std::collections::HashMap<String, usize> = std::collections::HashMap::new();
    for m in messages {
        let Some(role) = m.get("role").and_then(|v| v.as_str()) else {
            continue;
        };
        let Some(content) = m.get("content").and_then(|c| c.as_array()) else {
            continue;
        };
        if role == "assistant" {
            for block in content {
                if block.get("type").and_then(|t| t.as_str()) != Some("tool_use") {
                    continue;
                }
                let id = block
                    .get("id")
                    .and_then(|v| v.as_str())
                    .unwrap_or("")
                    .to_string();
                let name = block
                    .get("name")
                    .and_then(|v| v.as_str())
                    .unwrap_or("")
                    .to_string();
                if id.is_empty() || name.is_empty() {
                    continue;
                }
                let detail = block.get("input").map(|v| v.to_string());
                segments.push(PersistedSegment::Tool {
                    id: id.clone(),
                    name,
                    detail,
                    outputs: Vec::new(),
                    status: "running".to_string(),
                    summary: None,
                });
                tool_idx.insert(id, segments.len() - 1);
            }
        } else if role == "user" {
            for block in content {
                if block.get("type").and_then(|t| t.as_str()) != Some("tool_result") {
                    continue;
                }
                let id = block
                    .get("tool_use_id")
                    .and_then(|v| v.as_str())
                    .unwrap_or("");
                let is_error = block
                    .get("is_error")
                    .and_then(|v| v.as_bool())
                    .unwrap_or(false);
                let output_text = block.get("content").map(|v| {
                    v.as_str()
                        .map(|s| s.to_string())
                        .unwrap_or_else(|| v.to_string())
                });
                if let Some(&idx) = tool_idx.get(id) {
                    if let PersistedSegment::Tool {
                        outputs, status, ..
                    } = &mut segments[idx]
                    {
                        if let Some(o) = output_text {
                            outputs.push(o);
                        }
                        *status = if is_error { "failed" } else { "done" }.to_string();
                    }
                }
            }
        }
    }
    segments
}

/// Wrap the turn's tool transcript + assistant draft in a [`PersistedRun`]
/// shape so `response_lint::lint_run` can analyse it without needing a
/// finished recorder snapshot. Fields the lint rules ignore (`id`,
/// `started_at`, `model_*`, attachments, stats) stay at defaults.
fn build_partial_lint_run(messages: &[Value], draft: &str, provider: &str) -> PersistedRun {
    PersistedRun {
        id: String::new(),
        started_at: String::new(),
        ended_at: None,
        source: "live".to_string(),
        provider: provider.to_string(),
        model_id: String::new(),
        model_display_name: String::new(),
        user_text: String::new(),
        user_attachments: Vec::new(),
        assistant_segments: segments_from_messages(messages),
        final_text: draft.to_string(),
        stats: ChatStats::default(),
        error: None,
    }
}

// ============================================================================
// Tests — Sprint v6 Phase 6.
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use tokio::sync::mpsc;

    fn drain_deltas(rx: &mut mpsc::UnboundedReceiver<LlmDelta>) -> Vec<LlmDelta> {
        let mut out = Vec::new();
        while let Ok(d) = rx.try_recv() {
            out.push(d);
        }
        out
    }

    #[test]
    fn converter_text_only_user_message() {
        let input = vec![json!({"role": "user", "content": "what's my fire res?"})];
        let out = messages_openai_to_anthropic(&input);
        assert_eq!(out.len(), 1);
        assert_eq!(out[0]["role"], "user");
        let content = out[0]["content"].as_array().expect("array");
        assert_eq!(content.len(), 1);
        assert_eq!(content[0]["type"], "text");
        assert_eq!(content[0]["text"], "what's my fire res?");
    }

    #[test]
    fn converter_assistant_text_only() {
        let input = vec![
            json!({"role": "assistant", "content": "Your fire res is 75%."}),
            json!({"role": "assistant", "content": ""}),
        ];
        let out = messages_openai_to_anthropic(&input);
        // Empty assistant message should be skipped, leaving only the first.
        assert_eq!(out.len(), 1);
        assert_eq!(out[0]["role"], "assistant");
        let content = out[0]["content"].as_array().expect("array");
        assert_eq!(content.len(), 1);
        assert_eq!(content[0]["type"], "text");
    }

    #[test]
    fn converter_assistant_with_tool_calls_object_args() {
        let input = vec![json!({
            "role": "assistant",
            "content": "Checking your build…",
            "tool_calls": [{
                "id": "call_123",
                "function": {
                    "name": "get_active_build",
                    "arguments": {"refresh": false}
                }
            }]
        })];
        let out = messages_openai_to_anthropic(&input);
        assert_eq!(out.len(), 1);
        let content = out[0]["content"].as_array().expect("array");
        assert_eq!(content.len(), 2);
        assert_eq!(content[0]["type"], "text");
        assert_eq!(content[1]["type"], "tool_use");
        assert_eq!(content[1]["id"], "call_123");
        assert_eq!(content[1]["name"], "get_active_build");
        assert_eq!(content[1]["input"]["refresh"], false);
    }

    #[test]
    fn converter_assistant_with_tool_calls_string_args() {
        // Some Ollama models emit arguments as a JSON-encoded string.
        let input = vec![json!({
            "role": "assistant",
            "content": "",
            "tool_calls": [{
                "id": "call_str",
                "function": {
                    "name": "pob_calc",
                    "arguments": "{\"main_skill_only\": true}"
                }
            }]
        })];
        let out = messages_openai_to_anthropic(&input);
        let content = out[0]["content"].as_array().expect("array");
        // Empty text + 1 tool_use = 1 block.
        assert_eq!(content.len(), 1);
        assert_eq!(content[0]["type"], "tool_use");
        assert_eq!(content[0]["input"]["main_skill_only"], true);
    }

    #[test]
    fn converter_assistant_tool_call_missing_id_autogenerates() {
        let input = vec![json!({
            "role": "assistant",
            "content": "",
            "tool_calls": [{
                "function": {
                    "name": "wiki_parse",
                    "arguments": {"page": "Suppression"}
                }
            }]
        })];
        let out = messages_openai_to_anthropic(&input);
        let content = out[0]["content"].as_array().expect("array");
        assert_eq!(content[0]["type"], "tool_use");
        let id = content[0]["id"].as_str().unwrap();
        assert!(
            id.starts_with("ollama-wiki_parse-"),
            "expected autogenerated id, got: {id}"
        );
    }

    #[test]
    fn converter_assistant_multiple_tool_calls() {
        let input = vec![json!({
            "role": "assistant",
            "content": "Looking up two things…",
            "tool_calls": [
                {"id": "a", "function": {"name": "wiki_parse", "arguments": {}}},
                {"id": "b", "function": {"name": "pob_calc", "arguments": {}}}
            ]
        })];
        let out = messages_openai_to_anthropic(&input);
        let content = out[0]["content"].as_array().expect("array");
        // text + 2 tool_use blocks
        assert_eq!(content.len(), 3);
        assert_eq!(content[0]["type"], "text");
        assert_eq!(content[1]["type"], "tool_use");
        assert_eq!(content[1]["id"], "a");
        assert_eq!(content[2]["type"], "tool_use");
        assert_eq!(content[2]["id"], "b");
    }

    #[test]
    fn converter_tool_result_matches_preceding_tool_call() {
        let input = vec![
            json!({"role": "user", "content": "what's my dps?"}),
            json!({
                "role": "assistant",
                "content": "",
                "tool_calls": [{
                    "id": "call_42",
                    "function": {"name": "get_active_build", "arguments": {}}
                }]
            }),
            json!({
                "role": "tool",
                "name": "get_active_build",
                "content": "{\"key_stats\":{\"average_damage\":50000}}"
            }),
        ];
        let out = messages_openai_to_anthropic(&input);
        assert_eq!(out.len(), 3);
        // Third message should be a user tool_result with tool_use_id = "call_42".
        assert_eq!(out[2]["role"], "user");
        let content = out[2]["content"].as_array().expect("array");
        assert_eq!(content[0]["type"], "tool_result");
        assert_eq!(content[0]["tool_use_id"], "call_42");
        assert_eq!(
            content[0]["content"].as_str().unwrap(),
            "{\"key_stats\":{\"average_damage\":50000}}"
        );
    }

    #[test]
    fn converter_orphan_tool_result_skipped() {
        // tool result without a preceding tool_call: must be skipped silently
        // so downstream helpers don't see a phantom tool_use.
        let input = vec![
            json!({"role": "user", "content": "hi"}),
            json!({"role": "tool", "name": "get_active_build", "content": "{}"}),
        ];
        let out = messages_openai_to_anthropic(&input);
        // Only the user message survives.
        assert_eq!(out.len(), 1);
        assert_eq!(out[0]["role"], "user");
    }

    #[test]
    fn converter_drops_system_messages() {
        let input = vec![
            json!({"role": "system", "content": "You are Bestel."}),
            json!({"role": "user", "content": "hi"}),
        ];
        let out = messages_openai_to_anthropic(&input);
        assert_eq!(out.len(), 1);
        assert_eq!(out[0]["role"], "user");
    }

    #[test]
    fn count_fetch_tool_calls_on_converted_ollama_data() {
        // Build an Ollama-shaped message trace with two fetch calls
        // (wiki_parse, pob_calc) and one non-fetch (get_active_build).
        // After conversion, count_fetch_tool_calls should report 2.
        let input = vec![
            json!({"role": "user", "content": "audit my build"}),
            json!({
                "role": "assistant",
                "content": "",
                "tool_calls": [
                    {"id": "a", "function": {"name": "get_active_build", "arguments": {}}},
                ]
            }),
            json!({"role": "tool", "name": "get_active_build", "content": "{}"}),
            json!({
                "role": "assistant",
                "content": "",
                "tool_calls": [
                    {"id": "b", "function": {"name": "wiki_parse", "arguments": {}}},
                    {"id": "c", "function": {"name": "pob_calc", "arguments": {}}}
                ]
            }),
            json!({"role": "tool", "name": "wiki_parse", "content": "..."}),
            json!({"role": "tool", "name": "pob_calc", "content": "{}"}),
        ];
        let converted = messages_openai_to_anthropic(&input);
        assert_eq!(count_fetch_tool_calls(&converted), 2);
    }

    #[test]
    fn tool_transcript_from_converted_ollama_active_build() {
        // After conversion, ToolTranscript::from_messages should pick up
        // the get_active_build payload and expose it on `active_build`.
        let payload = "{\"identity\":{\"class\":\"Templar\"},\"defences\":{\"life\":5000}}";
        let input = vec![
            json!({
                "role": "assistant",
                "content": "",
                "tool_calls": [{
                    "id": "call_ab",
                    "function": {"name": "get_active_build", "arguments": {}}
                }]
            }),
            json!({"role": "tool", "name": "get_active_build", "content": payload}),
        ];
        let converted = messages_openai_to_anthropic(&input);
        let transcript = ToolTranscript::from_messages(&converted);
        assert!(transcript.active_build.is_some());
        let build = transcript.active_build.unwrap();
        assert_eq!(build["identity"]["class"], "Templar");
    }

    #[test]
    fn build_partial_lint_run_includes_provider_label() {
        let messages: Vec<Value> = vec![];
        let run_a = build_partial_lint_run(&messages, "draft", "anthropic");
        let run_o = build_partial_lint_run(&messages, "draft", "ollama");
        assert_eq!(run_a.provider, "anthropic");
        assert_eq!(run_o.provider, "ollama");
        assert_eq!(run_a.final_text, "draft");
        assert_eq!(run_a.source, "live");
    }

    #[test]
    fn shared_post_stream_emits_lint_findings_when_non_empty() {
        // Craft a transcript with a build-claim draft + zero get_active_build
        // calls — `BUILD_IDENTITY_REQUIRED` should fire.
        let (tx, mut rx) = mpsc::unbounded_channel();
        let messages: Vec<Value> = vec![];
        let draft = "Your build is squishy and you'll oom in 2s during pinnacle fights. \
                    Identity: defense=life, hit_model=crit.";
        let outcome = run_shared_post_stream(&messages, draft, &tx, "anthropic");
        assert_eq!(outcome.fetch_tool_calls, 0);
        let deltas = drain_deltas(&mut rx);
        assert!(
            deltas
                .iter()
                .any(|d| matches!(d, LlmDelta::LintFindings { .. })),
            "expected at least one LintFindings delta to be emitted, got {:?}",
            deltas
        );
    }

    #[test]
    fn shared_post_stream_skips_lint_emit_when_no_findings() {
        // A trivial draft that should not trigger any lint rule.
        let (tx, mut rx) = mpsc::unbounded_channel();
        let messages: Vec<Value> = vec![];
        let draft = "Hello.";
        let _ = run_shared_post_stream(&messages, draft, &tx, "anthropic");
        let deltas = drain_deltas(&mut rx);
        assert!(
            !deltas
                .iter()
                .any(|d| matches!(d, LlmDelta::LintFindings { .. })),
            "expected no LintFindings delta on trivial draft, got {:?}",
            deltas
        );
    }

    #[test]
    fn converter_handles_text_assistant_without_tool_calls() {
        // Pure text assistant message: should emerge as a single text block.
        let input = vec![json!({
            "role": "assistant",
            "content": "Here's the answer."
        })];
        let out = messages_openai_to_anthropic(&input);
        assert_eq!(out.len(), 1);
        let content = out[0]["content"].as_array().expect("array");
        assert_eq!(content.len(), 1);
        assert_eq!(content[0]["type"], "text");
        assert_eq!(content[0]["text"], "Here's the answer.");
    }
}
